version: "3.8"

services:
  db:
    image: satya678/python:dbimage
    ports:
      - "3306:3306"
    networks:
      - selfnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_service:
    image: satya678/python:authimage
    ports:
      - "5001:5001"
    networks:
      - selfnet

  book_service:
    image: satya678/python:bookimage
    ports:
      - "5002:5002"
    networks:
      - selfnet

  borrow_service:
    image: satya678/python:borrowimage
    ports:
      - "5003:5003"
    networks:
      - selfnet

  frontend:
    image: satya678/python:appimage
    ports:
      - "5000:5000"
    networks:
      - selfnet

networks:
  selfnet:
    driver: overlay
